### ISSUE TITLE
manual_delete does nothing

### ISSUE THREAD

**Issue by nfp007** [grke/burp#321]
if set in burp-server.conf or in clients configuration it does nothing leaving specified directory empty.
I used burp version 2.0.23
```
manual_delete=/tank/deleteme
```

**Comment by grke** [comment]
I have checked the code, and it seems that manual_delete is only invoked
when deleting rubble left behind when finalising a backup when hardlinked_archive=0.
It is not trying to use it when old backups are deleted.
I will make a change so that it does it for both.

Meanwhile, you should probably try to have fewer simultaneous backups going
to the same disk.

**Comment by grke** [comment]
Should now be fixed in git master.

**Comment by nfp007** [comment]
Hi, i installed newest version from master (2.0.23), but unluckily the issue remains the same.
Old backups are not deleted at all, stockpiling in client directories.
my exact setup on server is like follows:
<code>
mode = server
port = 4971
address = 0.0.0.0
status_port = 4972
status_address = 0.0.0.0
protocol = 1
dedup_group = default
monitor_browse_cache = 1
directory = /tank
clientconfdir = /etc/burp/clientconfdir
pidfile = /var/run/burp.server.pid
hardlinked_archive = 1
librsync = 0
manual_delete = /tank/deleteme
working_dir_recovery_method = resume
max_children = 4
max_status_children = 4
umask = 0022
syslog = 1
stdout = 0
logfile = /var/log/burp-server.log
client_can_delete = 1
client_can_force_backup = 1
client_can_list = 1
client_can_restore = 1
client_can_verify = 1
network_timeout = 36000
version_warn = 1
keep = 7
keep = 3
keep = 1
ca_conf = /etc/burp/CA.cnf
ca_name = burpCA
ca_server_name = burpserver
ca_burp_ca = /usr/sbin/burp_ca
ssl_cert_ca = /etc/burp/ssl_cert_ca.pem
ssl_cert = /etc/burp/ssl_cert-server.pem
ssl_key = /etc/burp/ssl_cert-server.key
ssl_key_password = password
ssl_dhfile = /etc/burp/dhfile.pem
timer_script = /etc/burp/timer_script

restore_client = angel.in-igloo.net
</code>

**Comment by grke** [comment]
On line 776 of src/server/protocol1/backup_phase4.c, try changing...

if(previous_backup && !hardlinked_current)

...to:

if(previous_backup)


Meanwhile, I think the slowness of deletion is probably due to you using ZFS with ZFS deduplication turned on. When deleting on a deduplicating filesystem, the filesystem needs to check whether there are any references left to the blocks that you are deleting the references for, and this takes a lot of time - especially on large filesystems. You will find that something like ext4 is much faster.

**Comment by grke** [comment]
Whoops, don't try the change that I mentioned above, it will move your latest backup to deleteme. I will have another go at fixing it.

**Comment by grke** [comment]
Fixed for next release.
