### ISSUE TITLE
Test failure on OSX

### ISSUE THREAD

**Issue by rubenk** [grke/burp#359]
I've been looking into the following test failure on OSX:
`utest/client/test_find.c:156:F:Core:test_find:0: Assertion '!mknod(tmp, mode, 100)' failed`

The initial idea was that this failed because mknod needs super-user privileges.
This is not the case, it's just that mknod can't create sockets on OSX.

I guess we need support for S_ISSOCK(statp.st_mode) in src/client/restore.c:restore_special?

The same failure happens on OpenBSD for what it's worth.

I also noticed that that same tests tests if it can create a fifo with mknod, but we always seem to do that with mkfifo.

**Comment by grke** [comment]
OK.
How do you create sockets on OSX without mknod?

**Comment by rubenk** [comment]
With socket(2)

**Comment by rubenk** [comment]
This works on Linux, Solaris and the BSD's as well.
I propose dropping the mknod code and just using mkfifo() for fifo's and socket() for unix sockets, since these are much more portable.

**Comment by grke** [comment]
I don't think socket(2) is what we want. It returns a file descriptor, and doesn't let you specify a location in the filesystem at which to create a node.

**Comment by grke** [comment]
Interestingly, bacula doesn't try to restore S_ISSOCK nodes at all, for any system:

         } else if (S_ISSOCK(attr->statp.st_mode)) {
             Dmsg1(200, "Skipping restore of socket: %s\n", attr->ofname);

**Comment by rubenk** [comment]
You can set the location of the socket in saddr.sun_path. You then need to bind(2) it and close(2) it. This will create a named socket. See for example https://troydhanson.github.io/network/Unix_domain_sockets.html

**Comment by grke** [comment]
I have merged a change that does what you suggested.
It seems to work on Linux. I don't know about others yet.

**Comment by rubenk** [comment]
Thanks, I'll give it a run on some other platforms shortly!

**Comment by rubenk** [comment]
This fixed the test case on OSX.

For FreeBSD, the test still fails because we test mknod for a fifo, instead of testing mkfifo:
```
utest/client/test_find.c:156:F:Core:test_find:0: Assertion '!mknod(tmp, mode, 100)' failed
```

Changing the '100' argument to 0 fixes this, since 0 is the only reasonably portable way as argument for a fifo according to Posix, but in my humble opinion we should stop using mknod and just test mkfifo instead.

**Comment by grke** [comment]
Update now in master.
Hopefully this issue can now be closed.

**Comment by grke** [comment]
Closing. Thanks for the tips.
