### ISSUE TITLE
server not starting after upgrade to 2.3.18

### ISSUE THREAD

**Issue by cbergmann** [grke/burp#837]
Hi,

after upgrade to 2.3.18 my server does not start.
Normally my server is called as `/usr/sbin/burp -c /etc/burp/burp-server.conf -F`. This exits immediately with exit code 255. If i start it with `strace` the last Lines are as follows:

```
setgroups(1, [999])                     = 0
getgid()                                = 0
setgid(999)                             = 0
getuid()                                = 0
setuid(999)                             = 0
exit_group(-1)                          = ?
+++ exited with 255 +++
```

From the changelog I saw that someting was changed in the setuid part of the code. Therefore I suspect that this might be a problem.

**Comment by grke** [comment]
Hello,

I think you are probably right about the new code.

From what I can tell of the new code, it shouldn't be taking effect unless you have added readall=1 to your server conf.

If you try to start like this:

```
/usr/sbin/burp -c /etc/burp/burp-server.conf -F -v
```

Is there anything useful in the output - does it say "could not set specified user 'something': something"? Can you post that output here?

The function that is involved with this is src/handy.c: chuser_and_or_chgrp(), so you could possibly add extra logp()s in there, to debug.

Are you setting a user and/or group in your server config? Can you post the output of this:

```
burp -c /etc/burp/burp.conf -t | grep -E 'user|group'
```

Thank you for reporting.

**Comment by grke** [comment]
Never mind, I think I have reproduced the problem.
Now making a fix.

**Comment by cbergmann** [comment]
Hi, thanks for the fast response. Adding -v does not change the response. The application crashes without any output. I have a user and group defined in my configuration. These are a user and group both called burp with the uid and gid 999. These names are correctly resolved and setgroups, setgid and setuid are called accordingly.
Can I somehow help with more debug? I attached my configuration. The only change is that I changed the domain to example.com.
[burp-server.conf](https://github.com/grke/burp/files/3920663/burp-server.conf.txt)

**Comment by grke** [comment]
Hello,

As I mentioned, I have reproduced and fixed the problem.
I have pushed the fix to the git master branch, so I will close this issue.
If there is still a problem, you are welcome to re-open this issue.

Thank you for taking the time to report the issue.

**Comment by cbergmann** [comment]
Hi, thanks for the fix. Will there be a release for this version sometime near or do I have to compile the fixed version from source?

**Comment by ziirish** [comment]
Hello,

I will build new "unofficial" packages for Ubuntu and Debian as soon as I can: 2.3.18-2

**Comment by cbergmann** [comment]
thank you @ziirish for your quick response. I will wait for the packages then.

**Comment by ziirish** [comment]
done

**Comment by cbergmann** [comment]
Hi,
thanks to both of you for the quick reaction. Unfortunately the problem persists. I still get exit code 255 after setuid. Is there anything I can do to help with debugging?

Kind regards
Clemens

**Comment by ziirish** [comment]
Sorry, my mistake... My build script still checked out the 2.3.18 tag...

I'm building new packages at the moment: 2.3.18-3

Thanks for the quick feedback.

**Comment by cbergmann** [comment]
Thank you the 2.3.18-3 seems to work.
